language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get install poppler-utils
install:
  - pip install pillow
  - pip install psutil
  - pip install memory_profiler
  - pip install codecov
script:
  - python tests.py
  - coverage run tests.py
  - sudo apt-get remove poppler-utils
  - coverage run -a tests.py
  - codecov
